### ISSUE TITLE
Issue creating creds with web ui 

### ISSUE THREAD

**Issue by jamesw4** [FunkeyFlo/ps5-mqtt#11]
### Description of the issue

A great add on - thanks. 

Having some issues creating creds with web ui. 

First time after add on starts always seems to timeout, all subsequent attempts even with new url and new pin fail with invalid request. 

### Addon version

0.6.2

### Platform

Core: core-2022.7.6
Supervisor: supervisor-2022.07.0
OS: Home Assistant OS 8.2

### Logs of the issue (if applicable)

Starting PS5-MQTT...
2022-07-24T21:50:44.910Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/PS5-948
2022-07-24T21:50:44.935Z @ha:ps5:webserver Server listening on PORT: 8645
2022-07-24T21:50:47.938Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/PS5-948
2022-07-24T21:50:50.751Z @ha:ps5:checkDevicesState Update HA
2022-07-24T21:50:50.783Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/PS5-948
2022-07-24T21:51:22.655Z @ha:ps5:webserver connecting to device: 'BC33298990B1'
2022-07-24T21:53:38.919Z @ha:ps5:webserver connecting to device: 'BC33298990B1'
2022-07-24T21:53:39.640Z @ha:ps5:webserver:playactor Registering with device via Remote Play.
2022-07-24T21:53:39.641Z @ha:ps5:webserver:playactor Go to Settings > System > Remote Play > Link Device
2022-07-24T21:53:39.641Z @ha:ps5:webserver:playactor Enter PIN here> 
2022-07-24T21:54:10.233Z @ha:ps5:error Error: Timeout
    at Timeout._onTimeout (/app/node_modules/playactor/dist/remoteplay/registration.js:90:51)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
2022-07-24T21:54:20.752Z @ha:ps5:webserver connecting to device: 'BC33298990B1'
2022-07-24T21:54:39.570Z @ha:ps5:webserver connecting to device: 'BC33298990B1'
2022-07-24T21:54:39.860Z @ha:ps5:error HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by FunkeyFlo** [comment]
Hi @jamesw4, I also saw this behaviour during my tests when the URL, acquired through authentication with Sony, had already been used with another request. 

Could you please confirm for me, once more, that you're performing the exact same steps as shown in the .gif in [this post](https://community.home-assistant.io/t/ps5-mqtt-control-playstation-5-devices-using-mqtt/441141#authentication-ui-v600-2)? Thanks!

**Comment by jamesw4** [comment]
Hi, exactly like that yes. I think I need to test playactor from another system. 

I got shell in the container and hitting same sort of issue when manually running playactor login in that it seems to accept url and pin but just hangs before finally timing out. 

Thanks

**Comment by FunkeyFlo** [comment]
Let me know what you end up discovering. I might be able to add a hint to the error to give the user a sense of what might be going wrong based on what you find. If you really need some help feel free to DM me on twitter.

**Comment by jamesw4** [comment]
Managed to get creds using another device and these work fine with the add on. 

It looks as if playactor at point of auth listens on port 9295 and waits for ps5 to connect to it, but can’t see where 9295 is being exposed in the container. 

Thanks.

**Comment by FunkeyFlo** [comment]
@jamesw4 are you still experiencing this issue?

**Comment by jamesw4** [comment]
@FunkeyFlo yeah - I’m ok until the functionality to provide the creds yourself vanishes. I was going to try do some packer capture and port probing to see if I can get a better idea of what’s going on.

**Comment by FunkeyFlo** [comment]
Version 0.6.3 was just released, could you check if the issue still exists on that version? Otherwise I suggest joining the [discord](https://discord.gg/BnmvYHvz5N) for more active help.

**Comment by jamesw4** [comment]
Will close for now - not had chance do to anything further but all is working well with the creds I got directly from playactor. Thanks.
