### ISSUE TITLE
Error updating to 0.6.3

### ISSUE THREAD

**Issue by DerHerzog7** [FunkeyFlo/ps5-mqtt#13]
### Description of the issue

Getting an error when trying to update to latest version. 

Error updating PS5 MQTT: Unknown error, see supervisor

### Addon version

0.6.3

### Platform

Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

### Logs of the issue (if applicable)

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:24:35 AM (5 occurrences)
Last logged: 11:56:31 AM

[547626435488] Error updating PS5 MQTT: Unknown error, see supervisor
[547641743520] Error updating PS5 MQTT: Unknown error, see supervisor
[547898014832] Error updating PS5 MQTT: Unknown error, see supervisor
[547915788928] Error updating PS5 MQTT: Unknown error, see supervisor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Unknown error, see supervisor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating PS5 MQTT: Unknown error, see supervisor

**Comment by FunkeyFlo** [comment]
Unfortunately the log doesn't say much. 🙁
Have you tried:
- installing other add-ons
- uninstalling the add on before installing
- restarting HA
- installing the edge version; the two versions should be the same at this time.
Otherwise I suggest joining the discord for more active help.

**Comment by UnknownUser6** [comment]
I have the same problem

**Comment by FunkeyFlo** [comment]
@UnknownUser6 sorry to hear that. But I urge you to not react to issues with "me too" and instead either:
- Use reactions on other comments like 👀 to express you are experiencing the same issue.
- Provide new/extra information such as logs to help others better understand the issue so we might fix it.

Also; did you try _all_ the steps I mentioned above?

**Comment by UnknownUser6** [comment]
@FunkeyFlo Sorry I somehow wanted to express it is not only one case. Now I know how. Reinstalling helped

**Comment by FunkeyFlo** [comment]
Since reinstalling helped I'm guessing it has to do with the fact that version [0.6.3](https://github.com/FunkeyFlo/ps5-mqtt/releases/tag/v0.6.3) switched from locally built docker files to images. Maybe the supervisor doesn't handle this upgrade path correctly. As such I'm closing this issue @DerHerzog7 please re-open if the issue persists
