### ISSUE TITLE
Account activity cannot be tracked / NPSSO cannot be exchanged for access token

### ISSUE THREAD

**Issue by FunkeyFlo** [FunkeyFlo/ps5-mqtt#153]
### Description of the issue

As reported in [this issue](https://github.com/achievements-app/psn-api/issues/105) on the psn-api github, sony changed the way NPSSO's can be exchanged for access tokens required to access PSN api's.

Until this issue is resolved account activity tracking will be unavailable.

### Addon version

1.3.0

### Platform

Every platform

### Logs of the issue (if applicable)

```
2022-12-13T16:27:19.900Z @ha:ps5:error Error: 
      There was a problem retrieving your PSN access code. Is your NPSSO code valid?
      To get a new NPSSO code, visit https://ca.account.sony.com/api/v1/ssocookie.
    
    at _callee$ (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:948:19)
    at tryCatch (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:144:40)
    at Generator.invoke [as _invoke] (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:375:22)
    at Generator.next (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:200:21)
    at asyncGeneratorStep (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:13:24)
    at _next (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:35:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by danielsmith89** [comment]
Does this have anything to do with my PSN account getting locked out (and password reset required)? I've had to do this twice since I enabled account tracking.

**Comment by FunkeyFlo** [comment]
No. This has to do with not being able to authenticate at all.
