### ISSUE TITLE
401:Unauthorized when tracking PSN activity

### ISSUE THREAD

**Issue by schumi2004** [FunkeyFlo/ps5-mqtt#157]
### Description of the issue

This is my first time using this addon and after setting it up few days back I wanted to test PSN account activity.
During testing I noticed some errors in logs and a 401:Unauthorized ~~but I think the errors and 401:Unauthorized are not related.~~
~~Because of the 401 i tried to remove my PSN account so it doesn't get locked but this failed (see logs).~~

Regarding the 401. I'm 100% sure i followed the steps but still the error pops-up.
~~The error: Unexpected end of JSON input. Repeated it self every few minutes last night.~~

### Addon version

1.3.1

### Platform

Home Assistant 2022.12.6
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.0 - latest

### Logs of the issue (if applicable)

~~Config save failure when trying to remove PSN account:
Failed to save add-on configuration, Invalid list for option 'psn_accounts' in PS5 MQTT (df123456_ps5_mqtt). Got {'mqtt': {}, 'logger': '@ha:ps5:*', 'device_check_interval': 5000, 'device_discovery_interval': 60000, 'account_check_interval': 5000, 'include_ps4_devices': False, 'psn_accounts': None}~~

```
Some errors found while checking logs:
2022-12-15T06:02:14.652Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-12-15T06:02:16.428Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/123456789
2022-12-15T06:02:22.214Z @ha:ps5:checkDevicesState Update HA
2022-12-15T06:02:22.222Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/123456789
2022-12-15T15:40:38.385Z @ha:ps5:checkDevicesState Update HA
2022-12-15T15:40:39.695Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/123456789
2022-12-15T15:40:40.392Z @ha:ps5:psn-api Unable to retrieve PSN information. API response: "401:Unauthorized"
```

**Comment by FunkeyFlo** [comment]
`401:Unauthorized` is probably a variant of  #153. Sony probably changed more stuff to screw up authentication again. I'm seeing it in my personal setup as well, since today. Will hit up the PSN dev community to see what's up.

Also;
1. If you see an issue, or something strange in the logs, please check the existing issues, discord and HA community thread to see if the error you're seeing has been reported before and what the solution/issue might be. 
2. The JSON error has been reported, and answered numerous times. The config error was asked and answered on the HA forum this week.
3. For separate issues _create separate issues_. Compound error reports don't help in providing precise answers and resolutions. 🙃

**Comment by schumi2004** [comment]
Thanks for clarification. I will check Discord and HA forum for the remaining issues.

**Comment by FunkeyFlo** [comment]
re-opened because authorization issue is still relevant.

**Comment by FunkeyFlo** [comment]
Closing issue due to inactivity/no longer receiving reports of this issue occuring.
