### ISSUE TITLE
Device state check fails when PS5 names contains non alpha-numeric or '-' , '_' characters.

### ISSUE THREAD

**Issue by dazza2924** [FunkeyFlo/ps5-mqtt#21]
### Description of the issue

Seems that the plugin has issues in communicating with the PlayStation 5, when it has an apostrophe in the name. The attached logs show that when there is an apostrophe in the PlayStation 5 name (under Settings on the PS5), it has issues connecting. However, when the apostrophe is removed from the PlayStation 5 name, it is able to connect. A successful result was obtained by renaming "Darren's PS5" to "Darren-PS5", so it could have also been the space in the original name causing the issue too.

### Addon version

0.6.4

### Platform

Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

### Logs of the issue (if applicable)

2022-07-31T01:34:30.628Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/Darren's PS5
2022-07-31T01:34:35.767Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:65:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-07-31T01:34:35.774Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/Darren's PS5
2022-07-31T01:34:40.926Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:65:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-07-31T01:34:40.933Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/Darren's PS5
2022-07-31T01:34:46.068Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:65:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-07-31T01:34:46.075Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/Darren's PS5
2022-07-31T01:34:51.305Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:65:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-07-31T01:34:51.316Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/Darren's PS5
2022-07-31T01:34:56.481Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:65:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-07-31T01:34:56.487Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/Darren's PS5
2022-07-31T01:35:01.629Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:65:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-07-31T01:35:01.636Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/Darren's PS5
2022-07-31T01:35:06.778Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:65:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-07-31T01:35:06.787Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/Darren's PS5
2022-07-31T01:35:11.923Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:65:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-07-31T01:35:11.932Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/Darren's PS5

**Comment by FunkeyFlo** [comment]
fixed with release of version 0.7.0.
