### ISSUE TITLE
Docker does not start

### ISSUE THREAD

**Issue by ic-dev21** [FunkeyFlo/ps5-mqtt#212]
### Description of the issue

I tried using the docker compose example shown in the documentation, unfortunately the docker does not start. 

### Addon version

1.3.1

### Platform

Core 2023.3.6

### Logs of the issue (if applicable)

Log file shows:

```
Starting PS5-MQTT...
2023-03-30T15:31:21.789Z @ha:ps5:error config could not be read from 'undefined'
/app/node_modules/mqtt/lib/client.js:1388
    const err = new Error('Connection refused: ' + errors[rc])
                ^
Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/app/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:549:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {

5
}
Starting PS5-MQTT...
2023-03-30T15:34:50.913Z @ha:ps5:error config could not be read from 'undefined'
/app/node_modules/mqtt/lib/client.js:1388
    const err = new Error('Connection refused: ' + errors[rc])
                ^
Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/app/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:549:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {

5
}
```

Docker compose:

```
version: '3'

services:
  ps5-mqtt:
    container_name: PS5-MQTT                            # choose whatever name you like
    image: ghcr.io/funkeyflo/ps5-mqtt/armv7:latest      # you can also use a specific version
    entrypoint: /config/run.sh                          # the file that will be executed at startup
    volumes:                                            # we will use this volume to get our custom startup script into the container
      - /home/*removed*/docker/ps5mqtt:/config
    network_mode: host                                  # changing/omiting this option WILL BREAK the app.
    environment:
      - MQTT_HOST=192.168.69.4                         # (ip)address of your mqtt broker
      - MQTT_PORT=1883                                  # port of your mqtt broker
      - MQTT_USERNAME=*removed*                         # username used for connecting to your mqtt broker
      - MQTT_PASSWORD=*removed*                     # password used for connecting to your mqtt broker

      - DEVICE_CHECK_INTERVAL=5000
      - DEVICE_DISCOVERY_INTERVAL=60000
      - ACCOUNT_CHECK_INTERVAL=5000

      - 'PSN_ACCOUNTS=[{"username": "MyPsnUser", "npsso":"npsso_value"}]'

      - INCLUDE_PS4_DEVICES=false

      - FRONTEND_PORT=8645

      - CREDENTIAL_STORAGE_PATH=/config/credentials.json
      - DEBUG=@ha:ps5:*
  ```

Folder structure
![Screen Shot 2023-03-30 at 11 38 38 AM](https://user-images.githubusercontent.com/108159253/228890045-2157c5cd-f2ec-4237-a4ca-c3a7f747271b.png)

Connection to the MQTT broker using MQTT explorer and the same credentials is functional.

**Comment by ic-dev21** [comment]
Noticed a typo in my mqtt password. Fixed.
