### ISSUE TITLE
link device does not work

### ISSUE THREAD

**Issue by sefininio** [FunkeyFlo/ps5-mqtt#233]
### Description of the issue

I have installed this service in docker variant - it works well, and the status is updated including the activity and attributes.
However, the power switch will not turn the PS5 on/off.
I went through the Link Device process, pasted the redirect link and the code.
The logs show this error:
```
05/14/2023 9:34:02 PM
2023-05-14T18:34:02.958Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/<redacted>/set/power
05/14/2023 9:34:05 PM
2023-05-14T18:34:05.562Z @ha:ps5:error Error: Registration error: 403: Forbidden: Other Error
05/14/2023 9:34:05 PM
    at Object.<anonymous> (/usr/local/lib/node_modules/playactor/dist/remoteplay/protocol.js:88:19)
05/14/2023 9:34:05 PM
    at Generator.next (<anonymous>)
05/14/2023 9:34:05 PM
    at fulfilled (/usr/local/lib/node_modules/playactor/dist/remoteplay/protocol.js:5:58)
05/14/2023 9:34:05 PM
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

### Addon version

1.3.1

### Platform

Core 2023.5.2
Installed with docker container

**Comment by FunkeyFlo** [comment]
Did you follow all the steps described/linked [here](https://github.com/FunkeyFlo/ps5-mqtt#the-log-is-showing-403-errors-when-i-try-to-turn-my-ps5-on-or-off)?

**Comment by sefininio** [comment]
Yes I have.
✅ From the home screen, select  [Settings] > [System] > [Remote Play], and then turn on [Enable Remote Play].
✅ To start Remote Play while your PS5 console is in rest mode, select  [Settings] > [System] > [Power Saving] > [Features Available in Rest Mode]. Then turn on [Stay Connected to the Internet] and [Enable Turning on PS5 from Network].


I then navigated to the ps5-mqtt GUI, where I followed the instructions to link device with the URL and link code.

In the ps5-mqtt GUI, I see the device, the state etc. In HA I see the state & activity.

Turning off the HA switch does nothing. It is turned off and immediately turned on again with no effect to the PS5.

**Comment by sefininio** [comment]
OK, I guess my bad. I did all the above again, and now it is working  🤷
