### ISSUE TITLE
NPSSO token gets invalidated quickly

### ISSUE THREAD

**Issue by bitman30** [FunkeyFlo/ps5-mqtt#240]
### Description of the issue

I have 4 accounts using the same PS5, so I am trying to add all 4 accounts to the integration, however, each time I add the NPSSO token for one account and also do the authentication via the web UI and reload the integration, another account loses its authentication and the logs show:
```
2023-05-28T08:42:07.434Z @ha:ps5:error Error: 
      There was a problem retrieving your PSN access code. Is your NPSSO code valid?
      To get a new NPSSO code, visit https://ca.account.sony.com/api/v1/ssocookie.
    
    at _callee$ (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:455:19)
    at tryCatch (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:80:17)
    at Generator._invoke (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:63:24)
    at Generator.next (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:105:21)
    at asyncGeneratorStep (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:304:24)
    at _next (/app/node_modules/psn-api/dist/psn-api.cjs.development.js:323:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-05-28T08:42:07.438Z @ha:ps5:error Account <accountName> retrieval failed. Activity for this account will not be tracked.
```
When I fix this user, another user which was already working properly (verified that I can get the sensor information on the title name etc...) loses its authentication, and when I go to grab the NPSSO token, it generates a new one.

### Addon version

1.3.1

### Platform

Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

**Comment by FunkeyFlo** [comment]
Did you use different (incognito) browsers for each account? If not; previous npsso's will be invalidated when signing out/signing into a different account in the same "session".

**Comment by bitman30** [comment]
@FunkeyFlo Thanks!
That did the trick, maybe worth adding this bit of information to the docs (or did I miss it?)
Another thing that I also noticed is that if you are logged in but you set the 'Appear offline', it will also not pick up the now playing information.

Thank you for a great integration :-)
