### ISSUE TITLE
PS4 Game activity not matched to PS5

### ISSUE THREAD

**Issue by dnestico** [FunkeyFlo/ps5-mqtt#27]
### Description of the issue

Just setup the addon and it seems to have connected except my activity isn't updating.

### Addon version

1.0.0

### Platform

Home Assistant core - 2022.8.2
Supervisor 2022.08.3
Operating System 8.4
Frontend 20220802.0 - latest

**Comment by FunkeyFlo** [comment]
You'll need to provide more information. Please provide:
- **Add-on Configuration** (redact any passwords)
- What do you mean by 'updating'? Does the sensor ever receive a value? Does it not change after receiving a value? Etc.
- Describe expected behaviour
- **Add-on logs** (the issue template doesn't specify them for fun 😉)

**Comment by dnestico** [comment]
Configuration:

mqtt:
  host: 192.168.2.117
  port: "1883"
  user: admin
  pass: **removed**
logger: "@ha:ps5:*"
device_check_interval: 1000
device_discovery_interval: 60000
account_check_interval: 4000
include_ps4_devices: false
psn_accounts:
  - username: davidnestico
    npsso: **removed**


Like I turned on my PS5 and opened God of War and it just stayed idle.

LOGS:

Starting PS5-MQTT...
2022-08-16T19:17:37.532Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T19:17:37.631Z @ha:ps5:webserver Server listening on PORT: 62286
2022-08-16T19:17:40.651Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T19:20:15.283Z @ha:ps5:checkDevicesState Update HA
2022-08-16T19:20:15.301Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T19:20:42.572Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:75:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-08-16T19:20:42.590Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T19:20:51.671Z @ha:ps5:checkDevicesState Update HA
2022-08-16T19:20:51.714Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T19:38:01.162Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:75:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-08-16T19:38:01.181Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T19:38:07.766Z @ha:ps5:checkDevicesState Update HA
2022-08-16T19:38:07.782Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T21:03:34.369Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:75:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-08-16T21:03:34.396Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T21:03:40.429Z @ha:ps5:checkDevicesState Update HA
2022-08-16T21:03:40.441Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T21:03:56.475Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:75:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-08-16T21:03:56.484Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T21:04:05.761Z @ha:ps5:checkDevicesState Update HA
2022-08-16T21:04:05.779Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T21:04:55.333Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:75:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-08-16T21:04:55.352Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T21:05:04.438Z @ha:ps5:checkDevicesState Update HA
2022-08-16T21:05:04.447Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T21:07:10.518Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:75:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2022-08-16T21:07:10.532Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310
2022-08-16T21:07:16.998Z @ha:ps5:checkDevicesState Update HA
2022-08-16T21:07:17.011Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C8818CE310

**Comment by FunkeyFlo** [comment]
Is your account `online` and not `appear offline`?

Have you tried setting the privacy setting: 
`Who can see your online status and what your currently playing.` to `anyone`?

Have you tried starting a PS5 only title? Like Astro's playroom, returnal, etc.?

A restart of the add-on might be required after making these changes.

**Comment by dnestico** [comment]
I started God of War aka a PS4 title, wonder if that's why, and will try restarting addon soon.

And I just changed my gaming history to "anyone" everything else was already on "anyone" except that was "friends only" until now. I will test this tonight.

**Comment by dnestico** [comment]
@FunkeyFlo 

Update:

I made all my settings "anyone" and I restarted addon, it looks like it works but only with PS5 games damn, any reason why it can't work with PS4 games and it just shows as idle?

With that being said how can I make my card look like yours with the game name and also cover?

<img width="133" alt="Screen Shot 2022-08-16 at 10 24 19 PM" src="https://user-images.githubusercontent.com/3034555/185020758-9487f0d2-3ce9-495f-b0a4-8a00db51a75a.png">

**Comment by FunkeyFlo** [comment]
Unfortunately not all PSN API's have been documented (by the community). It's not something that Sony officially supports themselves, outside of official partners like discord.

The coming weeks I probably won't have time to debug this so it might take a while for a fix to arrive.

P.s.: please don't clutter the thread with questions on different topics. For questions/issues related to the add-on open a new GitHub issue. How to use the entities the add-on supplies is probably a question for the discord.

**Comment by dnestico** [comment]
Alright, can I open a discussion with the question then instead? sorry.

And I mostly play PS5 games now anyways I just sometimes go back to PS4 games for trophy hunting reasons or if the game doesn't have a PS5 upgrade like warzone, so not a big deal for how long it takes to fix!

**Comment by FunkeyFlo** [comment]
Fix has been implemented an included in the next release

**Comment by dnestico** [comment]
Awesome!! Thanks for a quick fix!
