### ISSUE TITLE
PS5 MQTT wont start

### ISSUE THREAD

**Issue by Sakynet** [FunkeyFlo/ps5-mqtt#321]
### Description of the issue

After adding the repository, I start it, and after a few seconds, nothing happens.
Just have options START and UNISTALL.

### Addon version

1.3.1

### Platform

Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

### Logs of the issue (if applicable)

Starting PS5-MQTT...
2023-10-13T11:23:43.091Z @ha:ps5:webserver Server listening on PORT: 64526
2023-10-13T11:23:46.164Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/BC3329311A11
2023-10-13T11:43:04.517Z @ha:ps5:checkDevicesState Update HA
2023-10-13T11:43:04.539Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/BC3329311A11
2023-10-13T11:43:32.013Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2023-10-13T11:43:32.019Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/BC3329311A11
2023-10-13T11:43:38.761Z @ha:ps5:checkDevicesState Update HA
2023-10-13T11:43:38.772Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/BC3329311A11

**Comment by TheCrey** [comment]
How did you solve the issue ? 
It is stuck at me with 

Starting PS5-MQTT...

then nothing happens....
