### ISSUE TITLE
RejectingCredentialRequester.

### ISSUE THREAD

**Issue by mrkhachaturov** [FunkeyFlo/ps5-mqtt#325]
### Description of the issue

Followed all config according to documantation.
PS5 is discovered, show the state, but nothing else is working. I cannot even turn on or off ps5.
<img width="875" alt="image" src="https://github.com/FunkeyFlo/ps5-mqtt/assets/105451445/2f78663b-5258-4d46-8a04-1de9afa1dd83">

Mqtt pass and npsso are change to random letters. real npsso I have already obtained.

host: 192.168.2.144
port: "1883"
user: mqtt_user
pass: sjdhfjsfhs8dfsd9fjisfdjs8u

- username: Mr_Ruben
  npsso: 1p4asdasdadsjMjQvoD5OGMSRscrCNHaTXoITD4NTwQ5sjndfjkshfjkshdfjn88sud87ds98sdujsdn
  preffered_ps5: BC33295A4A66

### Addon version

1.3.1

### Platform

Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0

### Logs of the issue (if applicable)

Starting PS5-MQTT...
2023-10-20T03:09:26.401Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/BC33295A4A66
2023-10-20T03:09:26.421Z @ha:ps5:webserver Server listening on PORT: 63206
2023-10-20T03:09:29.420Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/BC33295A4A66
2023-10-20T03:09:59.556Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/BC33295A4A66/set/power
2023-10-20T03:09:59.962Z @ha:ps5:error Error: Not authenticated
    at RejectingCredentialRequester.<anonymous> (/usr/local/lib/node_modules/playactor/dist/credentials/rejecting-requester.js:24:19)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/playactor/dist/credentials/rejecting-requester.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/playactor/dist/credentials/rejecting-requester.js:4:12)
    at RejectingCredentialRequester.requestForDevice (/usr/local/lib/node_modules/playactor/dist/credentials/rejecting-requester.js:23:16)
    at CredentialManager.<anonymous> (/usr/local/lib/node_modules/playactor/dist/credentials.js:32:54)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/playactor/dist/credentials.js:5:58)

2023-10-20T03:10:14.562Z @ha:ps5:checkDevicesState Resume polling

**Comment by FunkeyFlo** [comment]
It seems [step 6](https://github.com/FunkeyFlo/ps5-mqtt#installation) was either not performed or failed. Please try performing it (again).

(The `npsso` is used to track online activity, not controlling the device.)
