### ISSUE TITLE
PS5 Activity sensor always showing idle state

### ISSUE THREAD

**Issue by medinnna** [FunkeyFlo/ps5-mqtt#400]
### Description of the issue

First of all, i want to thank you for work.

Now, for some reason the activity sensor is always showing idle, no matter what game/app is open, but the Power and Device status work as expected. The next is an error i found in the logs, but i don't know if is related to this issue.

Thanks in advance.

### Addon version

1.3.3

### Platform

Core: 2024.4.2
Supervisor: 2024.04.0
Operating System: 12.1

### Logs of the issue (if applicable)

```
2024-04-08T22:07:14.522Z @ha:ps5:checkDevicesState Update HA
2024-04-08T22:07:14.526Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C881C682C5
2024-04-08T22:07:40.251Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2024-04-08T22:07:40.253Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C881C682C5
2024-04-08T22:07:51.005Z @ha:ps5:checkDevicesState Update HA
```

**Comment by medinnna** [comment]
My bad 🙄 updating the npsso did the trick.
