### ISSUE TITLE
PS5 suddenly become unavailable

### ISSUE THREAD

**Issue by Osher-Levy** [FunkeyFlo/ps5-mqtt#409]
### Description of the issue

Suddenly my PS5 become unavailable. I tried to reconnect it from the add-on but it doesnt work.
On the logs of the addo-on I can see it have an issue with the .json file, but I can't tell what the problem exactlly.

### Addon version

1.3.3

### Platform

Core: 2024.5.4
Supervisor: 2024.05.1
Operating System: 12.3
Frontend: 20240501.1

### Logs of the issue (if applicable)

2024-05-20T15:25:29.605Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2024-05-20T15:25:29.607Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/00U3893DLS92

**Comment by RobertD502** [comment]
This is addressed in the [documentation](https://github.com/FunkeyFlo/ps5-mqtt?tab=readme-ov-file#can-devices-be-powered-onoff-fromto-other-modes-than-rest-mode)
> > Can devices be powered on/off from/to other modes than rest mode?
No. The underlying remote play protocol from sony does not support this.

You will see this error in your log when your PS5 is completely powered off (not in rest mode). In particular, [this line of code](https://github.com/FunkeyFlo/ps5-mqtt/blob/8657364905376f022a2dba291a29bc180ff692b3/ps5-mqtt/server/src/redux/sagas/check-devices-state.ts#L31) is where the error originates from. When your PS5 is completely off, `stdout` is completely empty and results in the error since you can't parse it. Since it relies on Sony's remote play protocol, it is seeing the same thing that you would see, when your PS5 is completely off, if you attempted to control your PS5 through the remote play app - you wouldn't be able to as it would be unavailable.

The only other time you may see this error, from my testing, is when using the switch entity to send your PS5 into rest mode - it occurs once and then resumes working as normal.

**Comment by xhemp** [comment]
@Osher-Levy I had the same issue, what fixed for me was going to settings, system, power saving, features available in rest mode and set stay connnected to the internet and enable turning on ps5 from network on.

**Comment by igorsantos07** [comment]
This is happening intermittently with my PS5, which is in sleep for a bunch of hours already. Thus, I'm not completely sure this is just a settings issue on the PS5:

```
2024-07-22T22:22:27.565Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:22:38.947Z @ha:ps5:checkDevicesState Update HA
2024-07-22T22:22:39.136Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:23:43.656Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2024-07-22T22:23:44.027Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:24:03.943Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    [...]
2024-07-22T22:24:04.491Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:24:18.430Z @ha:ps5:checkDevicesState Update HA
2024-07-22T22:24:18.778Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:24:59.463Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    [...]
2024-07-22T22:24:59.754Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:25:10.542Z @ha:ps5:checkDevicesState Update HA
2024-07-22T22:25:10.705Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:25:42.768Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    [...]
2024-07-22T22:25:43.916Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:26:03.604Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    [...]
2024-07-22T22:26:04.079Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:26:15.272Z @ha:ps5:checkDevicesState Update HA
2024-07-22T22:26:15.457Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:27:42.951Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    [...]
2024-07-22T22:27:43.392Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:27:58.523Z @ha:ps5:checkDevicesState Update HA
2024-07-22T22:27:58.748Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/5C9666998A10
2024-07-22T22:34:23.561Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    [...]
```
>Removed most of the repeated stack traces for brevity.
