### ISSUE TITLE
A lot of Zombie processes created by container

### ISSUE THREAD

**Issue by GAS85** [FunkeyFlo/ps5-mqtt#420]
### Description of the issue

Hey, I see that my system has over 7000 Zombie processes. 

```bash
ps aux | grep 'Z' | head
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        1036  0.0  0.0      0     0 ?        Z    Jun15   0:00 [node] <defunct>
root        1700  0.0  0.0      0     0 ?        Z    Jun15   0:00 [node] <defunct>
root        2327  0.0  0.0      0     0 ?        Z    Jun15   0:00 [node] <defunct>
root        2940  0.0  0.0      0     0 ?        Z    Jun15   0:00 [node] <defunct>
root        3433  0.0  0.0      0     0 ?        Z    Jun15   0:00 [node] <defunct>
root        3950  0.0  0.0      0     0 ?        Z    Jun15   0:00 [node] <defunct>
root        4500  0.0  0.0      0     0 ?        Z    Jun15   0:00 [node] <defunct>
root        5022  0.0  0.0      0     0 ?        Z    Jun15   0:00 [node] <defunct>
root        5531  0.0  0.0      0     0 ?        Z    Jun15   0:00 [node] <defunct>
```

After investigation I see that all of them are from the `node` this container.
```bash
pstree -p -s 1036
systemd(1)───containerd-shim(2850862)───node(2850892)───node(1036)
```
Restarting the container will kill all of them:
```bash
$ docker stop ps5-mqtt 
ps5-mqtt
$ ps aux | grep 'Z' | head
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
gas      3214070  0.0  0.0   7008  2108 pts/1    S+   15:18   0:00 grep --color=auto Z
```

### Addon version

1.3.3

### Platform

Docker on Ubuntu

### Logs of the issue (if applicable)

```
2024-06-16T13:13:33.067Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/04F778A51E6D
2024-06-16T13:13:53.090Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2024-06-16T13:13:53.090Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/04F778A51E6D
2024-06-16T13:14:13.119Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2024-06-16T13:14:13.120Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/04F778A51E6D
2024-06-16T13:14:33.142Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:78:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:35:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:16:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
2024-06-16T13:14:33.143Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/04F778A51E6D

**Comment by RobertD502** [comment]
**Theory:**

I'm assuming you are using the `entrypoint` that you changed in #413? If so, notice that the example `run.sh`, in the old documentation, includes `set -e`. Since you are directly calling the node command with your entrypoint and don't tell the shell to exit, when the JSON parsing error you shared above is encountered, the zombie processes pile up. I'd revert to using a `run.sh` file with the contents from before the documentation was changed, set your entrypoint to call said script, and test to see if you still experience zombie processes.

**Comment by GAS85** [comment]
I will test it.
But `set -e` will exit shell and this will leads to container restart, or? Theoretically my container will restart 7000 times instead of multiplying zombies?

**Comment by RobertD502** [comment]
No, the container itself is not restarted. If you look at the example `run.sh` script:

```sh
#!/bin/sh
set -e

echo Starting PS5-MQTT...
node app/server/dist/index.js
```

When the container starts, you see the `Starting PS5-MQTT...` message gets logged. If the docker container were to be restarting itself, you'd see this message logged after every time the error is encountered - during the container's start/restart, the `run.sh` script gets executed, but since this message, which is in the script, isn't seen, you know that the container isn't getting restarted when the node app encounters the error you showed.

**Comment by GAS85** [comment]
It is merged, thanks for help 😃
