### ISSUE TITLE
PS5 sometimes unresponsive to power on/off actions

### ISSUE THREAD

**Issue by SBRK** [FunkeyFlo/ps5-mqtt#448]
### Description of the issue

Sometimes when I change `switch.[device]_power` from on to off (or off to on) the PS5 does not turn on or off.

In the logs, I can see : (but I don't know if it's related)

```
2024-09-18T21:24:32.839Z @ha:ps5:checkDevicesState Resume polling
2024-09-18T21:24:43.644Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C881FDA026/set/power
2024-09-18T21:24:44.114Z @ha:ps5:error Error: Error[2] UNKNOWN_ERROR
    at Object.<anonymous> (/usr/local/lib/node_modules/playactor/dist/socket/helpers.js:76:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/playactor/dist/socket/helpers.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Any idea what's going on ?

### Addon version

1.4.0

### Platform

Core 2024.9.2
Supervisor 2024.09.1
Operating System 13.1

### Logs of the issue (if applicable)

2024-09-18T21:24:32.839Z @ha:ps5:checkDevicesState Resume polling
2024-09-18T21:24:43.644Z @ha:ps5:mqtt MQTT Message received ps5-mqtt/78C881FDA026/set/power
2024-09-18T21:24:44.114Z @ha:ps5:error Error: Error[2] UNKNOWN_ERROR
    at Object.<anonymous> (/usr/local/lib/node_modules/playactor/dist/socket/helpers.js:76:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/playactor/dist/socket/helpers.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by robertsze** [comment]
same issue here
