### ISSUE TITLE
account activity: invalid json response

### ISSUE THREAD

**Issue by PascalRiekenberg** [FunkeyFlo/ps5-mqtt#452]
### Description of the issue

2024-10-01T04:54:54.042Z @ha:ps5:error FetchError: invalid json response body at https://us-prof.np.community.playstation.net/userProfile/v1/users/me/profile2?fields=npId,onlineId,accountId,avatarUrls,plus,aboutMe,languagesUsed,trophySummary(@default,level,progress,earnedTrophies),isOfficiallyVerified,personalDetail(@default,profilePictureUrls),personalDetailSharing,personalDetailSharingRequestMessageFlag,primaryOnlineStatus,presences(@default,@titleInfo,platform,lastOnlineDate,hasBroadcastData),requestMessageFlag,blocking,friendRelation,following,consoleAvailability reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-10-01T04:54:54.042Z @ha:ps5:error Account 'NikasRiekenberg' retrieval failed. Activity for this account will not be tracked.

### Addon version

1.4.0

### Platform

 Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

### Logs of the issue (if applicable)

2024-10-01T04:54:54.042Z @ha:ps5:error FetchError: invalid json response body at https://us-prof.np.community.playstation.net/userProfile/v1/users/me/profile2?fields=npId,onlineId,accountId,avatarUrls,plus,aboutMe,languagesUsed,trophySummary(@default,level,progress,earnedTrophies),isOfficiallyVerified,personalDetail(@default,profilePictureUrls),personalDetailSharing,personalDetailSharingRequestMessageFlag,primaryOnlineStatus,presences(@default,@titleInfo,platform,lastOnlineDate,hasBroadcastData),requestMessageFlag,blocking,friendRelation,following,consoleAvailability reason: Unexpected token < in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2024-10-01T04:54:54.042Z @ha:ps5:error Account 'NikasRiekenberg' retrieval failed. Activity for this account will not be tracked.

**Comment by FunkeyFlo** [comment]
Are you sure your npsso is (still) valid?

**Comment by SuS-GitHub** [comment]
Yes i double checked. I realized that npsso is invalid yesterday. I updated this mornig to 1.4.0 and got a new npsso.

**Comment by PascalRiekenberg** [comment]
Yes, i double checked. I realized that npsso is invalid yesteray evenning. Today i updated to 1.4.0 and fetched new npsso.

**Comment by PascalRiekenberg** [comment]
Maybe due to problems with PSN today. Let me check when i am at home tonight.

**Comment by PascalRiekenberg** [comment]
I can see no errors in the log anymore.
